services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
      - ./data:/data
    ports:
      - "3401:8000"
    command: python main.py
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  frontend:
    build:
      context: ./frontend
    ports:
      - "3400:3400"
    volumes:
      - ./frontend:/app
      - ./data:/data
      - /app/node_modules
    command: npm run dev -- --host
